"""empty message

Revision ID: 8de4a3cdd2b2
Revises: 1550813dab77
Create Date: 2023-03-31 16:09:00.742118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de4a3cdd2b2'
down_revision = '1550813dab77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
        batch_op.drop_column('enable')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
        batch_op.drop_column('enable')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Integer(), nullable=True, comment='是否删除'))
        batch_op.drop_column('enable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
