"""add address field

Revision ID: ca5fa337b53f
Revises: 5997cb981383
Create Date: 2023-03-29 11:57:52.281639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5fa337b53f'
down_revision = '5997cb981383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('user_roles')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('update_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('enable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__users__3213E83FF93D2834')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('update_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('enable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__user_rol__3213E83FF678AB9A')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('update_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('enable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__roles__3213E83FA5031720')
    )
    # ### end Alembic commands ###
